### ISSUE TITLE
Feature request: simplify nested gtfs source loading

### ISSUE THREAD

**Issue by slvlirnoff** [transitland/gtfs#65]
In order to improve workflow with sources that have a permalink but might contains subfolders or nested zip with different names (the date for instance) it'd be good if the source within the zip is automatically detected and loaded. 

In short, when only one gtfs_source is detected and no fragment provided, load the gtfs source directly. This should work for nested zip and nested subfolder.

Potentially if multiple sources are detected and none specified as a fragment reject it with a AmbiguousSourceException < InvalidSourceException or similar instead of simply InvalidSourceException. for easier debugging.

**Comment by slvlirnoff** [comment]
would fix #64

**Comment by irees** [comment]
Thanks for the idea, @slvlirnoff

**Comment by slvlirnoff** [comment]
I'm happy to make a initial pull request, I've a spare hour now.

**Comment by irees** [comment]
@slvlirnoff Sure, that would be great! Please make it an option, e.g. similar to `strict: true`.

**Comment by slvlirnoff** [comment]
@irees Shoul I add a systematic check if no source specified and multiple roots exists (none being "") to return an AmbiguousSourceException?

**Comment by irees** [comment]
@slvlirnoff That sounds like a good addition; auto should only work if there's a single unambiguous answer.
