### ISSUE TITLE
source.routes return empty array

### ISSUE THREAD

**Issue by thestrauss3** [transitland/gtfs#68]
I am using GTFS to successfully grab the data for many feeds, however I've been having problems with some. Specifically when I do `source = GTFS::Source.build("https://transitfeeds-data.s3-us-west-1.amazonaws.com/public/feeds/national-park-service/617/20160720/gtfs.zip")` I get source  ```[2] pry(main)> source.routes
=> []```
I do have all the information for every other file in the .zip, just not routes. When I actually put the url into my browser and download the file, the routes.txt file is clearly filled. For some reason that data is not being passed.  

I have not yet tested this with any other feeds and I am going to try to resolve the issue myself, but I am still rather inexperienced.

**Comment by irees** [comment]
(Trying reply from email)

Hi,

Try passing in "strict: false", e.g. GTFS::Source.build(url, strict: false)

This will bypass some of the validation, and is commonly required for Feeds that aren't in perfect compliance with the spec.

**Comment by thestrauss3** [comment]
Thanks, I hadn't tried that. I'm gonna try to figure out exactly what's causing it cause it appears fine by my eyes
